### ISSUE TITLE
Content wrapped inside of ContextMenu gets invisible after navigating away

### ISSUE THREAD

**Issue by Flam3rboy** [dominicstop/react-native-ios-context-menu#34] opened 2022-01-30 00:38 UTC
I've first created an issue on [react-navigation](https://github.com/react-navigation/react-navigation/issues/10308), but found out that this issue is related to this library.

### Current behavior

I have a FlatList (with ``windowSize: 1``) of messages in my chat page, but when I navigate to a new page the items in this list turn blank and have to be rerendered to be visible again.

https://user-images.githubusercontent.com/34555296/151677107-527ea44e-7b3e-41ea-a9b2-ee37a0cdf2e9.mp4

Also interesting to note, when I navigate back, the messages stay visible, however when I navigate to a new page they turn blank in the process of navigating.

<table>
<tr>
<td>Navigate back to overview page:</td>
<td>Navigate to call page:</td>
</tr>
<tr>
<td><img width="200" src="https://user-images.githubusercontent.com/34555296/151677111-979843b6-7750-4f35-8efc-58ccb0b61c7f.png" /></td>
<td><img width="200" src="https://user-images.githubusercontent.com/34555296/151677110-54ab6d59-4c2e-4b8a-8f0f-00a54f84ebdb.png" /></td>
</tr>
</table>

### Expected behavior

The items shouldn't turn blank and have to be rerendered to be visible again.

### Environment

| package                                | version |
| -------------------------------------- | ------- |
|react-native-ios-context-menu|1.7.2
|@react-navigation/native|6.0.6
| @react-navigation/native-stack         | 6.2.5
| react-native-screens                   | 3.10.1
| react-native                           | 0.66.4
| node                                   | 16.10.0
| npm or yarn                            |  1.22.15
| OS | iOS 15.2.1

### Reproduction
[Snack](https://snack.expo.dev/YqeyCNL0H) doesn't work, because expo doesn't have ``react-native-ios-context-menu`` as a native dependency, but you can use the code to reproduce it:
```jsx
import * as React from 'react';
import { Text, View, Button, ScrollView } from 'react-native';
import { ContextMenu } from 'react-native-ios-context-menu';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import {
  NavigationContainer,
  useNavigationContainerRef,
} from '@react-navigation/native';

const Stack = createNativeStackNavigator();

function Chat({ navigation }) {
  return (
    <View style={{ flex: 1 }}>
      <Button title="Call" onPress={() => navigation.navigate('call')} />
      <ScrollView style={{ flexGrow: 1 }}>
        {['hi', 'test', 'nice', 'no', 'ok', 'goodbye', 'hello'].map((x) => (
          <ContextMenu
            previewConfig={{ previewType: 'DEFAULT', borderRadius: 0 }}
            menuConfig={{
              menuTitle: '',
              menuItems: [
                {
                  menuTitle: 'React',
                  menuItems: ['👍', '👎', '😂', '❤️', '🚀'].map((x) => ({
                    actionKey: 'react-' + x,
                    actionTitle: x,
                  })),
                  icon: {
                    type: 'IMAGE_SYSTEM',
                    imageValue: {
                      systemName: 'smiley',
                    },
                  },
                },
                {
                  menuTitle: 'Delete',
                  // actionKey: "delete",
                  // actionTitle: "Delete",
                  menuOptions: ['destructive'],
                  menuItems: [
                    {
                      actionKey: 'delete',
                      actionTitle: 'Confirm',
                      menuOptions: ['destructive'],
                      menuAttributes: ['destructive'],
                      icon: {
                        type: 'IMAGE_SYSTEM',
                        imageValue: {
                          systemName: 'trash.fill',
                        },
                      },
                    },
                  ],
                  icon: {
                    type: 'IMAGE_SYSTEM',
                    imageValue: {
                      systemName: 'trash.fill',
                    },
                  },
                },
              ],
            }}>
            <View style={{ padding: 10, margin: 5 }}>
              <Text>{x}</Text>
            </View>
          </ContextMenu>
        ))}
      </ScrollView>
    </View>
  );
}

function Call() {
  return (
    <View style={{ flex: 1 }}>
      <Text style={{ fontSize: 30 }}>Call Page</Text>
    </View>
  );
}

export default function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="chat" component={Chat} />
        <Stack.Screen name="call" component={Call} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}
```

**Comment by dominicstop** [comment] 2022-02-01 22:08
Hey sorry this took so long, but i fixed this in [v1.7.4
](https://github.com/dominicstop/react-native-ios-context-menu/releases/tag/v1.7.4) — this patch contains native code changes, so please don't forget to run `pod install` after updating ✨

please let me know if there are still problems and I'll re-open the issue — I haven't tested this thoroughly so there might be some edge-cases I've forgotten to consider (e.g. modals, interactive animations, etc).

**Comment by Flam3rboy** [comment] 2022-02-02 17:40
Awesome, thank you very much for time, the community and I appreciate the effort. Keep up the great work 🚀

**Comment by ferrannp** [comment] 2022-05-12 19:46
@dominicstop I think I am facing a similar issue. I have a `FlatList` and every item has a 3 dots icon, when you press it, you get the context menu.

Well, when you put the app into the background and come back after a while, the 3 dots are gone and you cannot press it at all. And the strangest thing is that i happens only sometimes (but quite often).

**Comment by dominicstop** [comment] 2022-05-12 22:11
@Flam3rboy let me take a look

what version of react-native + the library are you using?

and do you know if the bug still happens on production mode?

**Comment by ferrannp** [comment] 2022-05-13 16:25
Yep! It happens in production. I'm with react-native 0.66.x and the latest version of this library (1.7.4).

**Comment by ferrannp** [comment] 2022-05-14 14:48
@dominicstop I found a way to make this happen that might be related. If you start making the swipe back gesture to close the screen but then you swipe again (because you don't want to close it anymore). Then the `cleanup` functions gets called anyway.

**Comment by ferrannp** [comment] 2022-05-14 17:27
@dominicstop another example this happens. You have an app with bottom tabs. You are in one tab using your library. You change to another tab. Put the app in the background. Do something else. Come back to the app and go back to the first tab. Then the buttons using your library are invisible (they are not there).

**Comment by ferrannp** [comment] 2022-05-24 11:14
Hey @dominicstop. I patched the library as follows and it has been working for me so far:

```swift
  // Instead of viewWillDisappear
  override func viewDidDisappear(_ animated: Bool) {
    super.viewDidDisappear(animated);
    
    guard let parentVC = self.parentVC
    else { return };
    
    let navVC = self.navigationController;
    // if parent VC still exist in the stack, then it hasn't been popped yet
    let isPopping = navVC == nil || !(navVC?.viewControllers.contains(parentVC) ?? true);
    ...

```

**Comment by nm-ivanbasic** [comment] 2022-09-13 06:34
Still an issue with react-native-ios-context-menu: 1.12.1 and react native v0.67.

**Comment by fobos531** [comment] 2022-09-24 08:55
Hey @dominicstop , I can confirm that @ferrannp's patch resolves the issue for me, but in this case I have a slightly different problem. I have a tab view (implemented using react navigation's material top tab navigator) and the issue was me the same as for @ferrannp , as soon as I tried to navigate away from the tab view, the components that used the dropdown menu would disappear. By overridding the `viewDidDisappear` method instead of `viewWillDisappear`, the initial issue was solved, but now the issue became that the items would disappear as soon as the tab switching animation completed (which makes sense). How would you approach this? Can you clarify the purpose of the `RNINavigationEventsReportingViewController` ?

**Comment by ferrannp** [comment] 2022-09-24 10:04
It seems latest versions have no issue regarding this anymore 👍.

**Comment by dominicstop** [comment] 2022-09-24 19:00
@fobos531 hello, sorry for the late reply, haven't been active w/ OSS lately afdghsjdjaklfjklsghshgjdfogjdf

Basically, to prevent memory leaks, a cleanup routine needs to be triggered whenever the component unmounts.

The way I've implemented this is through a parent view controller that listens for when a view is removed (e.g. `RNINavigationEventsReportingViewController`). 

The `UIVIewController.viewWillDisappear` lifecycle method gets called whenever a view is hidden. Inside that method, we check if the parent `UINavigationController`'s navigation stack still contains the parent view controller.

If it does, then that means the current view controller hasn't been poppped yet, and instead, a new view controller has been pushed into the stack (and has taken focus).

Otherwise it means thats the view controller has been popped, and thus, it should notify its delegate (i.e. the `RNIContextMenu` instance) that it's going to be removed from the navigation stack.

This in turn will trigger the clean up routine. 

<br><br>

There are two assumptions here: The 1st one is that the parent view controller is the root view controller for the screen (which might not always be the case).

The 2nd assumption is that the reason for `UIVIewController.viewWillDisappear` to trigger is due to a `UINavigationController` instance changing the current active vc.

Unfortunately, if either one of these assumptions are false, then this will result w/ the cleanup routine being called when it doesn't need to be — causing the "disappearing" bug.

<br><br>

In the latest release (version `1.12.2`), I added a `internalCleanupMode` prop. This prop controls how the cleanup routine is triggered. 

You can set this prop to use 4 modes: `automatic`, `viewController`, `reactComponentWillUnmount`, and `disabled` — normally, you shouldn't need to fiddle with this prop, but I've added it as temp. fix for when this bug happens again (and I can't immediately fix it).

`viewController` mode will trigger the clean up routine via the `UIViewController.viewWillDisappear` lifecycle method, while `reactComponentWillUnmount` mode on the other hand, will trigger the clean up routine via the `componentWillUnmount` react lifecycle event.

By default, the `internalCleanupMode` prop is set to `automatic`. And currently, `automatic` mode defaults to using `reactComponentWillUnmount` mode — I might change this back to `viewController` once i fix all the edge cases.

<br><br>

If you are still experiencing this issue, try setting `internalCleanupMode` to `disabled` and reopen this issue (feel free to tag me if I take too long respond).

But for now, I'll be closing this issue asjhskflehfkehfiljds;jflsi @Flam3rboy sorry for late response, but i hope this fixes your issue xx

**Closed by dominicstop** 2022-09-24 19:00 UTC

**Comment by fobos531** [comment] 2022-09-26 14:25
Hey @dominicstop , just wanted to chime in and say that as far as I can see, the latest version work completely fine with the use case I described! Thanks a bunch! 🚀 🎉

**Comment by canfan** [comment] 2023-07-22 17:20
Hi – i'm seeing memory leaks with this library when wrapping <Image> or <FastImage> components with `<ContextMenuView>` – the memory is never released, which is very visible with GIFs.  

I've tried the internal `internalCleanupMode`s and none fix this issue. Is there are usage pattern that can get around this issue?
