### ISSUE TITLE
Swift compiler errors

### ISSUE THREAD

**Issue by FrankFundel** [dominicstop/react-native-ios-context-menu#7] opened 2021-01-09 15:41 UTC
I get these strange errors after installing the package.

![](https://i.ibb.co/YBTPcR2/Screenshot-1.png)

Does anyone know what the issue is? I could install it perfectly on another newer project.

Kind regards,
Frank

**Comment by dominicstop** [comment] 2021-01-09 15:51
This is the first time I'm encountering this error 😅

Could you post what RN version you're using, and your Xcode version? I'll try making a fresh project to reproduce.
This a long shot, but maybe it's related to [1.1.2 Xcode Build Error (Undefined symbol)](https://github.com/dominicstop/react-native-ios-context-menu#112-xcode-build-error-undefined-symbol)?

In the meantime, I'm gonna do some debugging... 😔

**Comment by FrankFundel** [comment] 2021-01-09 17:10
I'm on:
react-native-cli: 2.0.1
react-native: 0.61.5
and XCode 11.5

Clean build + Cleared derivedData.
Maybe it has something to do with that: https://stackoverflow.com/questions/40040570/swift-compiler-error-on-pods
I will try out tomorrow thank you for your help.

**Comment by dominicstop** [comment] 2021-01-10 00:25
Forgot to post before I went to sleep 😴, but I tried installing the library on a fresh RN app:
1. Created new RN project (the latest ver. is: `0.63.4`)
2. Tried to run the app but got: `Undefined symbol: (extension in UIKit)`

![Screen Shot 2021-01-10 at 1 37 52 AM](https://user-images.githubusercontent.com/18517029/104111309-5cbc5180-531b-11eb-8a71-dd19fbcd9d03.png)

3. Followed [1.1.2 Xcode Build Error (Undefined symbol) ](https://github.com/dominicstop/react-native-ios-context-menu#112-xcode-build-error-undefined-symbol), added an empty swift file, did a clean build, and ran the app

![Screen Shot 2021-01-10 at 7 54 42 AM](https://user-images.githubusercontent.com/18517029/104111314-6776e680-531b-11eb-851e-1706fe450dde.png)

4. I couldn't reproduce the error you got 😔

---

I've just read your reply, and I think that it might have something to do with RN `0.61.5` + Xcode `11.5`?
My current problem is that I only have 4gb's of space left, so I can't download Xcode 11 right now 😭

But looking at the error again, it seems like Xcode is can't find `UIMenu` in `UIKit` (so it's the same error as "undefined symbol" but with a different message...) 

So it could have something to do with `Library Search Paths` build setting again, but I am not sure. Have you tried creating a fresh RN project and following [1.1.2 Xcode Build Error (Undefined symbol) ](https://github.com/dominicstop/react-native-ios-context-menu#112-xcode-build-error-undefined-symbol)?

For now I'm going to try installing the library on `react-native: 0.61.5` 😅

**Comment by dominicstop** [comment] 2021-01-10 02:50
Hello, forgot to post this before I fell asleep last night 😴
 
I created a fresh RN project (the latest ver. is `0.63.4`) to try and reproduce the error:
1. Ran: `npx react-native init contextMenuTest6v0634`
2. Made sure that it builds/runs
3. Installed the library: `yarn add react-native-ios-context-menu` and `cd ios && pod install`
4. Tried to build the app and encountered this error:

![Screen Shot 2021-01-10 at 1 37 52 AM](https://user-images.githubusercontent.com/18517029/104112778-ae6dd780-532d-11eb-8bd6-8b69c88b7045.png)

5. Followed [1.1.2 Xcode Build Error (Undefined symbol)](https://github.com/dominicstop/react-native-ios-context-menu#112-xcode-build-error-undefined-symbol), added an empty swift file, did a clean build, and run the app

![Screen Shot 2021-01-10 at 7 54 42 AM](https://user-images.githubusercontent.com/18517029/104112779-b0d03180-532d-11eb-93c3-4887975706a0.png)

6. Couldn't reproduce the error 😔

Gonna try again with RN `0.61.5` later...

**Comment by dominicstop** [comment] 2021-01-10 02:54
So maybe the problem is with Xcode `11.5` and  RN `0.63.4` ? I don't have enough space to install another version of Xcode haha, so I'm going to use github actions:
1. Ran: `npx react-native init contextMenuTest7v0615  --version 0.61.5`
2. Made sure that it runs/builds, and then [published the repo to github](https://github.com/dominicstop/ContextMenuTest7-0.61.5)
3. Made a [github action](https://github.com/dominicstop/ContextMenuTest7-0.61.5/blob/main/.github/workflows/build-app.yml) that builds the app using Xcode `11.5`
4. Did a test run and [triggered the github action](https://github.com/dominicstop/ContextMenuTest7-0.61.5/actions/runs/474868583) to make sure it works
5. Installed `react-native-ios-context-menu` on the test project ([commit link](https://github.com/dominicstop/ContextMenuTest7-0.61.5/commit/1b031c4ac712da1e4f0d22bceb06b467ba1def48)):
    * Installed the library: `yarn add react-native-ios-context-menu`
    * Bumped the test project's deployment target from `iOS 9.0` -> `iOS 10.0` to fix the pod error: `[!] CocoaPods could not find compatible versions for pod "react-native-ios-context-menu": [...] but they required a higher minimum deployment.`
    * Followed [1.1.1 Xcode Build Error (Swift)](https://github.com/dominicstop/react-native-ios-context-menu#111-xcode-build-error-swift) to fix the pod error: `[!] Unable to determine Swift version for the following pods: "react-native-ios-context-menu" does not specify a Swift version and none of the targets ("contextMenuTest7v0615") integrating it have the "SWIFT_VERSION" attribute set. [...]`
    * Followed [1.1.3 Cocoapods Static Libraries Error](https://github.com/dominicstop/react-native-ios-context-menu#113-cocoapods-static-libraries-error) to fix pod error: `The Swift pod "react-native-ios-context-menu" depends upon "React-Core", which does not define modules.  [...]`
    * Ran `pod install`

6. Tried building the app locally on Xcode and encountered no errors so far:

![image](https://user-images.githubusercontent.com/18517029/104113160-d3644980-5331-11eb-9fa1-a49e6d357134.png)

7. [Triggered the github build action](https://github.com/dominicstop/ContextMenuTest7-0.61.5/actions/runs/474968641) to test if it still builds on Xcode `11.5`

**Comment by dominicstop** [comment] 2021-01-10 03:09
I finally was able to reproduce your error 😅

The [github action](https://github.com/dominicstop/ContextMenuTest7-0.61.5/runs/1675438023?check_suite_focus=true) failed to build the project with the following error:

![image](https://user-images.githubusercontent.com/18517029/104113361-fd1e7000-5333-11eb-8bcc-d43f2dfe7041.png)

![image](https://user-images.githubusercontent.com/18517029/104113365-0f001300-5334-11eb-8afa-101abf7aa43f.png)

![image](https://user-images.githubusercontent.com/18517029/104113375-263f0080-5334-11eb-9420-c8795dd07ea4.png)

[Link to full logs](https://pipelines.actions.githubusercontent.com/viQqffwlj4L11756IXkSDKaJRI5LAUwM7HDY9YWVtF0zZpwu9S/_apis/pipelines/1/runs/3/signedlogcontent/3?urlExpires=2021-01-10T03%3A06%3A52.3807630Z&urlSigningMethod=HMACV1&urlSignature=XBVSecMDUlSdVYNNabZ0Q1G%2BkhTlYvfQG0AC8L7%2Fhk8%3D)

---

The next step is to figure out what went wrong 😅

**Comment by dominicstop** [comment] 2021-01-10 09:30
I've found the solution, but you aren't going to like it 😔 
(skip to the end if you don't want to see the explanation haha)
* I finally was able to build the [test app](https://github.com/dominicstop/ContextMenuTest7-0.61.5) using Xcode 11.5 using this [GH action](https://github.com/dominicstop/ContextMenuTest7-0.61.5/blob/main/.github/workflows/Build-App-2.yml) (here's a [link](url) to the build output).
* In the build errors, I have noticed that Xcode was complaining about the iOS-14 specific API's of `UIMenu` (so at the very least, Xcode was aware that `UIKit.UIMenu` exists, just not the iOS 14 version of it).
* That's why there were only errors regarding `RCTContextMenuButton` because it was using the context menu API's for `UIButton` that were introduced in iOS 14.

<br>

* It turns out that it was problem with the Xcode Swift toolchain. In the [`Build App w/ Swift 5.3` GH action](https://github.com/dominicstop/ContextMenuTest7-0.61.5/blob/main/.github/workflows/Build-App-2.yml), it's using the swift 5.3 toolchain.
* **Swift 5.3** is important because that's the version of swift that was released with iOS 14 (this is also the reason why the same app builds on Xcode 12, but fails to build on Xcode 11. Xcode 12 is using a newer version of swift).
* In other words, certain framework features (such as `UIKit.UIMenu`) are tied to a the version of swift that Xcode is using (any mismatch causes the build to fail, presumably because the newer API's aren't declared in the headers).

<br>

So the steps to fix this are the same as before:

> 
> 1. Ran: `npx react-native init contextMenuTest7v0615  --version 0.61.5`
> 2. Made sure that it runs/builds, and then [published the repo to github](https://github.com/dominicstop/ContextMenuTest7-0.61.5)
> 3. Made a [github action](https://github.com/dominicstop/ContextMenuTest7-0.61.5/blob/main/.github/workflows/build-app.yml) that builds the app using Xcode `11.5`
> 4. Did a test run and [triggered the github action](https://github.com/dominicstop/ContextMenuTest7-0.61.5/actions/runs/474868583) to make sure it works
> 5. Installed `react-native-ios-context-menu` on the test project ([commit link](https://github.com/dominicstop/ContextMenuTest7-0.61.5/commit/1b031c4ac712da1e4f0d22bceb06b467ba1def48)):
>    
>    * Installed the library: `yarn add react-native-ios-context-menu`
>    * Bumped the test project's deployment target from `iOS 9.0` -> `iOS 10.0` to fix the pod error: `[!] CocoaPods could not find compatible versions for pod "react-native-ios-context-menu": [...] but they required a higher minimum deployment.`
>    * Followed [1.1.1 Xcode Build Error (Swift)](https://github.com/dominicstop/react-native-ios-context-menu#111-xcode-build-error-swift) to fix the pod error: `[!] Unable to determine Swift version for the following pods: "react-native-ios-context-menu" does not specify a Swift version and none of the targets ("contextMenuTest7v0615") integrating it have the "SWIFT_VERSION" attribute set. [...]`
>    * Followed [1.1.3 Cocoapods Static Libraries Error](https://github.com/dominicstop/react-native-ios-context-menu#113-cocoapods-static-libraries-error) to fix pod error: `The Swift pod "react-native-ios-context-menu" depends upon "React-Core", which does not define modules.  [...]`
>    * Ran `pod install`
> 6. Tried building the app locally on Xcode and encountered no errors so far:

But if you are using Xcode 11, you have to change the swift version that Xcode is using to at least: `Swift 5.3`
* Based on this [article](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiXtJ_OhJHuAhUrE6YKHSVYDrcQFjACegQIBRAC&url=https%3A%2F%2Fmedium.com%2Fxcblog%2Fswitching-swift-versions-inside-xcode-using-toolchains-755b28831c43&usg=AOvVaw1qBvZgd1RdO8Y-1QFXou0k), it's quite a lengthy process...
* You can either A: upgrade to Xcode 12, B: change your Xcode's toolchain that uses swift 5.3, or C: just use a different library (honestly, this is not worth all the hassle 😔)

---

I'm sorry I could't find a better solution, but this is something that is out of my abilities. The problem is with the version of Xcode you are using (and the fact that this library is using iOS 14 specific API's... ☹️)

<br>

I'm going to take a nap haha hope you find a solution that you are happy with, best of luck! ✨

**Comment by FrankFundel** [comment] 2021-01-10 09:53
Thank you for your awesome work so far 😀 Your solution is a bit confusing to me because on another project it works using the same XCode version. Maybe I can specify in my project which version of Swift to use? (maybe the project uses an older swift version because I have another pod in it which also uses swift)

**Comment by dominicstop** [comment] 2021-01-10 10:58
I'm sorry, this library is a mess haha 😔 (I'll take a look at this later, and do some more tests)

<br>

At the mean time, what did you do, and what errors did you encounter? I don't mind if you just paste the entire error/logs + build settings haha (it'll help with debugging). I'll follow along step by step and I'll try to reproduce the errors 😅

<br>

This would be a lot easier it i could install Xcode 11 (but I only have 4GB's of space left 🤣)

**Comment by FrankFundel** [comment] 2021-01-10 12:28
Nooo this library is really good. I described what I did in the comment above, I have not logs :/
When was the last version that used Swift 5.0 instead of Swift 5.3? I need ContextButton :(

**Comment by dominicstop** [comment] 2021-01-11 10:02
Here's what I've found after some testing haha
* For **Xcode 11.5** it uses: `Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)`
* For **Xcode 12.3** it uses: `Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)`

<br>

I'm a noob at Xcode but I can't figure how to make this work... I'm afraid that I'll end up breaking something if i mess with the build settings haha

It looks like the simplest solution is to just upgrade to `Xcode 12.3`. I didn't want to update, but I've been using it for a while and it's pretty good!

---

In the meantime, I'm going to try and set the podspec for this library to: `s.swift_version = '5.3'` and try to install it using `Xcode 11.5`

**Closed** 2021-01-11 11:10 UTC
