### ISSUE TITLE
navigation.push

### ISSUE THREAD

**Issue by ZerakPalani** [dominicstop/react-native-ios-context-menu#38] opened 2022-04-16 23:22 UTC
Using contextMenuButton on a screen, but this screen also has some buttons(navigation.push used here) somewhere else (not even related to the contextMenu) but it seems like if you go to a navigation.push() and then go back to the previous screen that has the contextMenu, the contextMenu is removed and becomes a blank/empty space.

I only found 1 article related to this issue, seems like not many have tried navigation.push() with contextMenu.
The ones who reported this issue ended up realizing that this module caused the issue so they decided to remove it, but for me, I want to keep using this module so if you can fix this for me then it's perfect!

Thank you!

**Comment by Flam3rboy** [comment] 2022-08-29 20:42
possible duplicate of #34?

**Comment by nandorojo** [comment] 2022-10-07 23:26
I think this is solved now from #34.

**Comment by ZerakPalani** [comment] 2022-10-29 18:06
Thank you for solving this issue!

**Closed** 2022-10-29 18:06 UTC
